### ISSUE TITLE
Unsupported sites?

### ISSUE THREAD

**Issue by idriskhenchil** [joshterrill/paywall-reader#2]
It's mentioned that there's an Unsupported sites section, where can I find that?

**Comment by joshterrill** [comment]
I just removed it a couple of weeks ago because I figured out a way to make it work for all the sites that were in it. Is there a new one you had in mind?

**Comment by idriskhenchil** [comment]
No, I do not have one in mind. I was just curious as to why a site would and wouldn't be supported.

**Comment by joshterrill** [comment]
Yeah, I updated the README accordingly. I was able to figure out a way to get news for the sites that were previously there, and I forgot that there was a note at the bottom of the README referencing that section that was removed. Apologies for the confusion.
