### ISSUE TITLE
Bloomberg article not showing up (2024)

### ISSUE THREAD

**Issue by Ash53212** [joshterrill/paywall-reader#5]
I tried to copy & paste a Bloomberg article URL, but it only gave me a 404 Error. I don't know if this is a bug, or if it can't read it right now.

**Comment by joshterrill** [comment]
It appears that the HTML layout for Bloomberg's data has changed, I'll make an update to the codebase this week to accommodate this.

**Comment by joshterrill** [comment]
This has been resolved in the latest version and deployed to https://reader.dangerous.dev

The article body parsing got way more complicated since this was originally written, but it should all work now, including images, and embeddables such as soundcloud links and videos.
